using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using System.Web.Http.Cors;

namespace COMP586Backend.Controllers
{
    // Autogenerated API project code. It defaults to this controller on startup.
    [EnableCors(origins: "*", headers: "*", methods: "*")]
    [Route("api/[controller]")]
    public class ValuesController : Controller
    {
        // GET api/values
        [EnableCors(origins: "*", headers: "*", methods: "*")]
        [HttpGet]
        public IEnumerable<string> Get()
        {
            return new string[] { "value1", "value2" };
        }

        // GET api/values/5
        [EnableCors(origins: "*", headers: "*", methods: "*")]
        [HttpGet("{id}")]
        public string Get(int id)
        {
            return "value";
        }


        // POST api/values
        [EnableCors(origins: "*", headers: "*", methods: "*")]
        [HttpPost]
        public void Post([FromBody]string value)
        {
        }

        // PUT api/values/5
        [EnableCors(origins: "*", headers: "*", methods: "*")]
        [HttpPut("{id}")]
        public void Put(int id, [FromBody]string value)
        {
        }

        // DELETE api/values/5
        [EnableCors(origins: "*", headers: "*", methods: "*")]
        [HttpDelete("{id}")]
        public void Delete(int id)
        {
        }
    }
}
